version: '3'

services:
  app:
    container_name: vollie
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '3000:3000'
      - '8080:8080'
      - '80:80'
    restart: unless-stopped

volumes:
  vollie-app: {}